2020-11-02 03:13:27,486:DEBUG:certbot._internal.main:certbot version: 1.9.0
2020-11-02 03:13:27,487:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/usr/share/nginx/html/letsencrypt', '--email', 'rpi.iot.2020@gmail.com', '--agree-tos', '--no-eff-email', '-d', 'rpi-iot.duckdns.org']
2020-11-02 03:13:27,488:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2020-11-02 03:13:27,549:DEBUG:certbot._internal.log:Root logging level set at 20
2020-11-02 03:13:27,550:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2020-11-02 03:13:27,552:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2020-11-02 03:13:27,565:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7fd6da382d30>
Prep: True
2020-11-02 03:13:27,566:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7fd6da382d30> and installer None
2020-11-02 03:13:27,566:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2020-11-02 03:13:27,673:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2020-11-02 03:13:27,677:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2020-11-02 03:13:28,648:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2020-11-02 03:13:28,649:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Nov 2020 03:13:28 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "nslyz-f_n-8": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2020-11-02 03:13:28,651:DEBUG:acme.client:Requesting fresh nonce
2020-11-02 03:13:28,651:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2020-11-02 03:13:28,888:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2020-11-02 03:13:28,890:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Nov 2020 03:13:28 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 00037YmUTKFElyWGib_dgP4TeIbr5mSHXWYbX2HDJi811hI
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2020-11-02 03:13:28,891:DEBUG:acme.client:Storing nonce: 00037YmUTKFElyWGib_dgP4TeIbr5mSHXWYbX2HDJi811hI
2020-11-02 03:13:28,892:DEBUG:acme.client:JWS payload:
b'{\n  "contact": [\n    "mailto:rpi.iot.2020@gmail.com"\n  ],\n  "termsOfServiceAgreed": true\n}'
2020-11-02 03:13:28,908:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-acct:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAiandrIjogeyJuIjogInc2NkY5dkNQS0FOVk41QnBCRzNhWVZ1RWREeEk1MWNtWXE3UzdKZWkySzQ4WlRGSTUwcXBkZGh3clp5N05DdXJ0aTRadEUzQnBGbUhnTWhwZHFNazZKd1dJTVhtLUJMd25CdXY2YjNwNXAxTE9vNVVWeXVSOGprc2NtdG9mckpqMnktRzNQazUxY25rdXdYSXdBa3ZHazg2Uzd2MEVmei0tMVdFSERGQVczWnpkM3lQbDlqV1ZWNV9ZMmRwRUEyaHNpU0ZzNVhlV2lFRnRDZWtJM3VmZTUzb19KYkhfR200a08wUDNSWmR5eTNWR2NHZUFKWGlMcDJMdUhTeUYwR0g1QUtIaHFqdWNkajBZTlBtYnctcEs0elEwSzN0dnRBVTVZUUI1SXU0cTNNdDNwbVJ0bTUtMm5Ca3RuT1lqWmlKamNZYlhablAyVmZSek9hVFZUak1oUSIsICJlIjogIkFRQUIiLCAia3R5IjogIlJTQSJ9LCAibm9uY2UiOiAiMDAwMzdZbVVUS0ZFbHlXR2liX2RnUDRUZUlicjVtU0hYV1liWDJIREppODExaEkiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1hY2N0In0",
  "signature": "pWpLtjCEaYnQJcVsXHBr3VEepcbYzYdqyNj3dcJZGQRnbtkrqSD6oHnKExNcqq4e745wDN55C0yF89zkFY07QikkVmsjdoYy61nBlQo9Mud9PwdjpmU9XYsZQYg9yAz4qJYPp22p5gtn36mPAgFo6mdBz-4SPyuzgB4LradQ2IsWS5D4CDU3aD3ZDTyIvRJ4_oQnfNsmEkD_r5_voZo2FznEuZ2OIeB9jd1OAxan92GURwzkAiyBc7-ykM_Z8jXWqTi43-qGyu3aqSMUB0QMht_l-blFl4DM7W-Pd1DoxnkNdYk6jW6uGcrGRyPm-q0OHx7QUjsvauVBpGxxp6FRNA",
  "payload": "ewogICJjb250YWN0IjogWwogICAgIm1haWx0bzpycGkuaW90LjIwMjBAZ21haWwuY29tIgogIF0sCiAgInRlcm1zT2ZTZXJ2aWNlQWdyZWVkIjogdHJ1ZQp9"
}
2020-11-02 03:13:29,182:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-acct HTTP/1.1" 201 564
2020-11-02 03:13:29,183:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Mon, 02 Nov 2020 03:13:29 GMT
Content-Type: application/json
Content-Length: 564
Connection: keep-alive
Boulder-Requester: 101051429
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf>;rel="terms-of-service"
Location: https://acme-v02.api.letsencrypt.org/acme/acct/101051429
Replay-Nonce: 0004XsNWCaKiGjitZzz1sRVSSaal5ODOFOdNK7egWb0CFYk
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "key": {
    "kty": "RSA",
    "n": "w66F9vCPKANVN5BpBG3aYVuEdDxI51cmYq7S7Jei2K48ZTFI50qpddhwrZy7NCurti4ZtE3BpFmHgMhpdqMk6JwWIMXm-BLwnBuv6b3p5p1LOo5UVyuR8jkscmtofrJj2y-G3Pk51cnkuwXIwAkvGk86S7v0Efz--1WEHDFAW3Zzd3yPl9jWVV5_Y2dpEA2hsiSFs5XeWiEFtCekI3ufe53o_JbH_Gm4kO0P3RZdyy3VGcGeAJXiLp2LuHSyF0GH5AKHhqjucdj0YNPmbw-pK4zQ0K3tvtAU5YQB5Iu4q3Mt3pmRtm5-2nBktnOYjZiJjcYbXZnP2VfRzOaTVTjMhQ",
    "e": "AQAB"
  },
  "contact": [
    "mailto:rpi.iot.2020@gmail.com"
  ],
  "initialIp": "60.53.241.89",
  "createdAt": "2020-11-02T03:13:29.034251825Z",
  "status": "valid"
}
2020-11-02 03:13:29,184:DEBUG:acme.client:Storing nonce: 0004XsNWCaKiGjitZzz1sRVSSaal5ODOFOdNK7egWb0CFYk
2020-11-02 03:13:29,188:DEBUG:certbot._internal.reporter:Reporting to user: Your account credentials have been saved in your Certbot configuration directory at /etc/letsencrypt. You should make a secure backup of this folder now. This configuration directory will also contain certificates and private keys obtained by Certbot so making regular backups of this folder is ideal.
2020-11-02 03:13:29,194:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=JWKRSA(key=<ComparableRSAKey(<cryptography.hazmat.backends.openssl.rsa._RSAPublicKey object at 0x7fd6da37cd30>)>), contact=('mailto:rpi.iot.2020@gmail.com',), agreement=None, status='valid', terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/101051429', new_authzr_uri=None, terms_of_service='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'), 5d3ee078da7cf6246f5d859f4c2f98b7, Meta(creation_dt=datetime.datetime(2020, 11, 2, 3, 13, 29, tzinfo=<UTC>), creation_host='f3cef6fea34b', register_to_eff=None))>
2020-11-02 03:13:29,197:INFO:certbot._internal.main:Obtaining a new certificate
2020-11-02 03:13:29,443:DEBUG:certbot.crypto_util:Generating key (2048 bits): /etc/letsencrypt/keys/0000_key-certbot.pem
2020-11-02 03:13:29,452:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0000_csr-certbot.pem
2020-11-02 03:13:29,455:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "rpi-iot.duckdns.org"\n    }\n  ]\n}'
2020-11-02 03:13:29,462:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTAxMDUxNDI5IiwgIm5vbmNlIjogIjAwMDRYc05XQ2FLaUdqaXRaenoxc1JWU1NhYWw1T0RPRk9kTks3ZWdXYjBDRllrIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIifQ",
  "signature": "P1fQJ562OIJFxpBKIFXjVOQrb-RNLrEHOKjqvJyUtIaJ2TkqDiPLpgIRmqzNcK00LqAMCMfO8b7K7KhXAuOtvUwrdLfmx53SFdHcZTSMn_qroRyKzjxREAQxtiPRi7-GcTUsX17M-b3vDbSYbD4j5GafsypT1miXobZhCSwv1LtuGSlDnNAN01t3KmbXsKfLGx3KTWeHsZR9nRIf-cSoIbProoUPYgF6niyQune3hz21-EpiyMlHGnmOJ_7p0D7PzApctGdK6fVQICmUndOjZTfdf3rHNRyA61RHl3XmLIWaoTaMcVPJUFdCTgA3DxCIYSHnIBh7A0kUq21LnmlosA",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogInJwaS1pb3QuZHVja2Rucy5vcmciCiAgICB9CiAgXQp9"
}
2020-11-02 03:13:29,732:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 350
2020-11-02 03:13:29,735:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Mon, 02 Nov 2020 03:13:29 GMT
Content-Type: application/json
Content-Length: 350
Connection: keep-alive
Boulder-Requester: 101051429
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/101051429/5993131599
Replay-Nonce: 0004wKM9pmZ8BfXUq1yxMAsADNwUR40VOz-5gCRPsqJ3OeI
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2020-11-09T03:13:29.577023588Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "rpi-iot.duckdns.org"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/8302478148"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/101051429/5993131599"
}
2020-11-02 03:13:29,736:DEBUG:acme.client:Storing nonce: 0004wKM9pmZ8BfXUq1yxMAsADNwUR40VOz-5gCRPsqJ3OeI
2020-11-02 03:13:29,745:DEBUG:acme.client:JWS payload:
b''
2020-11-02 03:13:29,752:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/8302478148:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTAxMDUxNDI5IiwgIm5vbmNlIjogIjAwMDR3S005cG1aOEJmWFVxMXl4TUFzQUROd1VSNDBWT3otNWdDUlBzcUozT2VJIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My84MzAyNDc4MTQ4In0",
  "signature": "buE7IVA9vsIsyty_GnEZTtbPT9nSdIW57JZRmnFBvKphdfIxRXaQQ71r_5Z5NZFsKKaPQ5OhcwM2UFqnRSTTPxbkeYK_9pl8YQPAL5lFiWMJWMMEDygANtQU8-jzsQQVzHI54r4GXXv6Wxnvjixo9gtu9fYZCVFadc0M0jef1QUNsUwOreWnI08D11IoZYwhQ-PXemLQfeqTN5W1JE7zURfNulCi1FIJ6wZ6B0LcTbeO8YWD_qkWN0F-Om_IF3qdFZOyAyZJEx0EaP7Uf-TYpRILR0sS888fDBe1SCUonj7vsm2xPf9waRVKNk_4uSwhQim76jZTcTW_tJh34-_dSA",
  "payload": ""
}
2020-11-02 03:13:30,106:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/8302478148 HTTP/1.1" 200 797
2020-11-02 03:13:30,108:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Nov 2020 03:13:29 GMT
Content-Type: application/json
Content-Length: 797
Connection: keep-alive
Boulder-Requester: 101051429
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0004WURRMjIhu3by7Xw9GKc7MdmYJJwNXhJ8FjxyzeMJTrY
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "rpi-iot.duckdns.org"
  },
  "status": "pending",
  "expires": "2020-11-09T03:13:29Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8302478148/QHZp2w",
      "token": "bV2ZFTI9YWFQ7E3kcj4h5hEtGQJYitrKG_mj2Wfto64"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8302478148/vbl_8g",
      "token": "bV2ZFTI9YWFQ7E3kcj4h5hEtGQJYitrKG_mj2Wfto64"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8302478148/01_ObA",
      "token": "bV2ZFTI9YWFQ7E3kcj4h5hEtGQJYitrKG_mj2Wfto64"
    }
  ]
}
2020-11-02 03:13:30,109:DEBUG:acme.client:Storing nonce: 0004WURRMjIhu3by7Xw9GKc7MdmYJJwNXhJ8FjxyzeMJTrY
2020-11-02 03:13:30,110:INFO:certbot._internal.auth_handler:Performing the following challenges:
2020-11-02 03:13:30,111:INFO:certbot._internal.auth_handler:http-01 challenge for rpi-iot.duckdns.org
2020-11-02 03:13:30,112:INFO:certbot._internal.plugins.webroot:Using the webroot path /usr/share/nginx/html/letsencrypt for all unmatched domains.
2020-11-02 03:13:30,112:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge
2020-11-02 03:13:30,124:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge/bV2ZFTI9YWFQ7E3kcj4h5hEtGQJYitrKG_mj2Wfto64
2020-11-02 03:13:30,125:INFO:certbot._internal.auth_handler:Waiting for verification...
2020-11-02 03:13:30,126:DEBUG:acme.client:JWS payload:
b'{}'
2020-11-02 03:13:30,134:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/8302478148/QHZp2w:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTAxMDUxNDI5IiwgIm5vbmNlIjogIjAwMDRXVVJSTWpJaHUzYnk3WHc5R0tjN01kbVlKSndOWGhKOEZqeHl6ZU1KVHJZIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9jaGFsbC12My84MzAyNDc4MTQ4L1FIWnAydyJ9",
  "signature": "PnGqzQXXpziFOmAYtUq9gsxNwsGj-62ah1d_hP5d6MWye9fQFS5RGFlAs_Feg3S76N0CEmUa45q8F4EgA6WnWcnOVkRzSbNv86orMVolERVJyEFqq2KueZtUfDbqKKMXZnJqxt0Q5aBYho06-zYozZLzPEA57iwKBpeI6Tsp3Jtj1Rjvax8K5BjFHwwUG_tNZt_MNoIyYpGl4cIGZJHsYrW-3KuLNrBdaYKFb-6ibxjBxS7Dza5s7rFPqsehwBtNvU6fBf7lPsPCX_nDACH-2pDBtnDbhf6L-av_spRYJ9Y0YFF0BYn6htL4FeIpKtjgtb9yhdytYTWGshdKB2DnFQ",
  "payload": "e30"
}
2020-11-02 03:13:30,380:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/8302478148/QHZp2w HTTP/1.1" 200 185
2020-11-02 03:13:30,383:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Nov 2020 03:13:30 GMT
Content-Type: application/json
Content-Length: 185
Connection: keep-alive
Boulder-Requester: 101051429
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz-v3/8302478148>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/8302478148/QHZp2w
Replay-Nonce: 00037ysadIWOww_quFytVHVmp_fDRdjkC-AGIofqrA60im4
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8302478148/QHZp2w",
  "token": "bV2ZFTI9YWFQ7E3kcj4h5hEtGQJYitrKG_mj2Wfto64"
}
2020-11-02 03:13:30,384:DEBUG:acme.client:Storing nonce: 00037ysadIWOww_quFytVHVmp_fDRdjkC-AGIofqrA60im4
2020-11-02 03:13:31,387:DEBUG:acme.client:JWS payload:
b''
2020-11-02 03:13:31,396:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/8302478148:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTAxMDUxNDI5IiwgIm5vbmNlIjogIjAwMDM3eXNhZElXT3d3X3F1Rnl0VkhWbXBfZkRSZGprQy1BR0lvZnFyQTYwaW00IiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My84MzAyNDc4MTQ4In0",
  "signature": "Oxy1MA2TwuyLvV2Kplwop2j6-2SjxtGbiYcsa0gPuYVfTxix3krFzBaY7C6SxR4tWYIbB9RhdGOc9rHIWaz92thFnsiU0hRAFbJnoAUVtliCT4CxvcTuYQH1nAwIobKwNgi5I_LO1ARItzRyfdfXhQ6_cJHgYLAYG4zyUyMzdODd5fUrPG0an5oJ-FWmr2UoEpRqQb3-GlHgy520yJ-HIFp8OFnHv1gWJfbC6iDk18A6YmBQFMW6LezFtczsQHgc9Z7cu3m4XBXI34AvlWWk7_z5jJp-RJqMS9Bowm5TctVgwmqve4_ZzJaGn-KWBaWgQkBjPzfoousBzur5yjaxmg",
  "payload": ""
}
2020-11-02 03:13:31,646:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/8302478148 HTTP/1.1" 200 982
2020-11-02 03:13:31,650:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 02 Nov 2020 03:13:31 GMT
Content-Type: application/json
Content-Length: 982
Connection: keep-alive
Boulder-Requester: 101051429
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0004uJNOIYSUssWRxfndniyzRj1ljdq_uKeoCn_Pj3bgFbU
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "rpi-iot.duckdns.org"
  },
  "status": "invalid",
  "expires": "2020-11-09T03:13:29Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:connection",
        "detail": "Fetching http://rpi-iot.duckdns.org/.well-known/acme-challenge/bV2ZFTI9YWFQ7E3kcj4h5hEtGQJYitrKG_mj2Wfto64: Connection refused",
        "status": 400
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8302478148/QHZp2w",
      "token": "bV2ZFTI9YWFQ7E3kcj4h5hEtGQJYitrKG_mj2Wfto64",
      "validationRecord": [
        {
          "url": "http://rpi-iot.duckdns.org/.well-known/acme-challenge/bV2ZFTI9YWFQ7E3kcj4h5hEtGQJYitrKG_mj2Wfto64",
          "hostname": "rpi-iot.duckdns.org",
          "port": "80",
          "addressesResolved": [
            "60.53.241.89"
          ],
          "addressUsed": "60.53.241.89"
        }
      ]
    }
  ]
}
2020-11-02 03:13:31,652:DEBUG:acme.client:Storing nonce: 0004uJNOIYSUssWRxfndniyzRj1ljdq_uKeoCn_Pj3bgFbU
2020-11-02 03:13:31,653:WARNING:certbot._internal.auth_handler:Challenge failed for domain rpi-iot.duckdns.org
2020-11-02 03:13:31,653:INFO:certbot._internal.auth_handler:http-01 challenge for rpi-iot.duckdns.org
2020-11-02 03:13:31,654:DEBUG:certbot._internal.reporter:Reporting to user: The following errors were reported by the server:

Domain: rpi-iot.duckdns.org
Type:   connection
Detail: Fetching http://rpi-iot.duckdns.org/.well-known/acme-challenge/bV2ZFTI9YWFQ7E3kcj4h5hEtGQJYitrKG_mj2Wfto64: Connection refused

To fix these errors, please make sure that your domain name was entered correctly and the DNS A/AAAA record(s) for that domain contain(s) the right IP address. Additionally, please check that your computer has a publicly routable IP address and that no firewalls are preventing the server from communicating with the client. If you're using the webroot plugin, you should also verify that you are serving files from the webroot path you provided.
2020-11-02 03:13:31,655:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2020-11-02 03:13:31,655:DEBUG:certbot._internal.error_handler:Calling registered functions
2020-11-02 03:13:31,656:INFO:certbot._internal.auth_handler:Cleaning up challenges
2020-11-02 03:13:31,656:DEBUG:certbot._internal.plugins.webroot:Removing /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge/bV2ZFTI9YWFQ7E3kcj4h5hEtGQJYitrKG_mj2Wfto64
2020-11-02 03:13:31,657:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2020-11-02 03:13:31,658:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/opt/certbot/src/certbot/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1362, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1243, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 122, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 418, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 351, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 398, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2020-11-02 03:13:31,661:ERROR:certbot._internal.log:Some challenges have failed.
